// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fury/incentive/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AccumulationTime stores the previous reward distribution time and its corresponding collateral type
type AccumulationTime struct {
	CollateralType           string    `protobuf:"bytes,1,opt,name=collateral_type,json=collateralType,proto3" json:"collateral_type,omitempty"`
	PreviousAccumulationTime time.Time `protobuf:"bytes,2,opt,name=previous_accumulation_time,json=previousAccumulationTime,proto3,stdtime" json:"previous_accumulation_time"`
}

func (m *AccumulationTime) Reset()         { *m = AccumulationTime{} }
func (m *AccumulationTime) String() string { return proto.CompactTextString(m) }
func (*AccumulationTime) ProtoMessage()    {}
func (*AccumulationTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_da10610f52b06a94, []int{0}
}
func (m *AccumulationTime) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccumulationTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccumulationTime.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccumulationTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccumulationTime.Merge(m, src)
}
func (m *AccumulationTime) XXX_Size() int {
	return m.Size()
}
func (m *AccumulationTime) XXX_DiscardUnknown() {
	xxx_messageInfo_AccumulationTime.DiscardUnknown(m)
}

var xxx_messageInfo_AccumulationTime proto.InternalMessageInfo

// GenesisRewardState groups together the global state for a particular reward so it can be exported in genesis.
type GenesisRewardState struct {
	AccumulationTimes  AccumulationTimes  `protobuf:"bytes,1,rep,name=accumulation_times,json=accumulationTimes,proto3,castrepeated=AccumulationTimes" json:"accumulation_times"`
	MultiRewardIndexes MultiRewardIndexes `protobuf:"bytes,2,rep,name=multi_reward_indexes,json=multiRewardIndexes,proto3,castrepeated=MultiRewardIndexes" json:"multi_reward_indexes"`
}

func (m *GenesisRewardState) Reset()         { *m = GenesisRewardState{} }
func (m *GenesisRewardState) String() string { return proto.CompactTextString(m) }
func (*GenesisRewardState) ProtoMessage()    {}
func (*GenesisRewardState) Descriptor() ([]byte, []int) {
	return fileDescriptor_da10610f52b06a94, []int{1}
}
func (m *GenesisRewardState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisRewardState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisRewardState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisRewardState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisRewardState.Merge(m, src)
}
func (m *GenesisRewardState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisRewardState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisRewardState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisRewardState proto.InternalMessageInfo

// GenesisState is the state that must be provided at genesis.
type GenesisState struct {
	Params                      Params                      `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	USDFRewardState             GenesisRewardState          `protobuf:"bytes,2,opt,name=usdf_reward_state,json=usdfRewardState,proto3" json:"usdf_reward_state"`
	JinxSupplyRewardState       GenesisRewardState          `protobuf:"bytes,3,opt,name=jinx_supply_reward_state,json=jinxSupplyRewardState,proto3" json:"jinx_supply_reward_state"`
	JinxBorrowRewardState       GenesisRewardState          `protobuf:"bytes,4,opt,name=jinx_borrow_reward_state,json=jinxBorrowRewardState,proto3" json:"jinx_borrow_reward_state"`
	DelegatorRewardState        GenesisRewardState          `protobuf:"bytes,5,opt,name=delegator_reward_state,json=delegatorRewardState,proto3" json:"delegator_reward_state"`
	SwapRewardState             GenesisRewardState          `protobuf:"bytes,6,opt,name=swap_reward_state,json=swapRewardState,proto3" json:"swap_reward_state"`
	USDFMintingClaims           USDFMintingClaims           `protobuf:"bytes,7,rep,name=usdf_minting_claims,json=usdfMintingClaims,proto3,castrepeated=USDFMintingClaims" json:"usdf_minting_claims"`
	JinxLiquidityProviderClaims JinxLiquidityProviderClaims `protobuf:"bytes,8,rep,name=jinx_liquidity_provider_claims,json=jinxLiquidityProviderClaims,proto3,castrepeated=JinxLiquidityProviderClaims" json:"jinx_liquidity_provider_claims"`
	DelegatorClaims             DelegatorClaims             `protobuf:"bytes,9,rep,name=delegator_claims,json=delegatorClaims,proto3,castrepeated=DelegatorClaims" json:"delegator_claims"`
	SwapClaims                  SwapClaims                  `protobuf:"bytes,10,rep,name=swap_claims,json=swapClaims,proto3,castrepeated=SwapClaims" json:"swap_claims"`
	SavingsRewardState          GenesisRewardState          `protobuf:"bytes,11,opt,name=savings_reward_state,json=savingsRewardState,proto3" json:"savings_reward_state"`
	SavingsClaims               SavingsClaims               `protobuf:"bytes,12,rep,name=savings_claims,json=savingsClaims,proto3,castrepeated=SavingsClaims" json:"savings_claims"`
	EarnRewardState             GenesisRewardState          `protobuf:"bytes,13,opt,name=earn_reward_state,json=earnRewardState,proto3" json:"earn_reward_state"`
	EarnClaims                  EarnClaims                  `protobuf:"bytes,14,rep,name=earn_claims,json=earnClaims,proto3,castrepeated=EarnClaims" json:"earn_claims"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_da10610f52b06a94, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AccumulationTime)(nil), "fury.incentive.v1beta1.AccumulationTime")
	proto.RegisterType((*GenesisRewardState)(nil), "fury.incentive.v1beta1.GenesisRewardState")
	proto.RegisterType((*GenesisState)(nil), "fury.incentive.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("fury/incentive/v1beta1/genesis.proto", fileDescriptor_da10610f52b06a94)
}

var fileDescriptor_da10610f52b06a94 = []byte{
	// 789 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0xbb, 0x4b, 0xd9, 0x9d, 0x6c, 0x9b, 0xcd, 0x90, 0xdd, 0x0d, 0x59, 0xc9, 0x29, 0xdd,
	0x15, 0x44, 0x3d, 0xd8, 0x6a, 0xe0, 0xc8, 0x05, 0x53, 0x7e, 0x8a, 0x4a, 0x95, 0x53, 0x7a, 0x40,
	0x48, 0xd6, 0x38, 0x99, 0x98, 0xa9, 0x6c, 0x8f, 0x99, 0x19, 0xe7, 0xc7, 0x8d, 0x23, 0xc7, 0xfe,
	0x01, 0x48, 0xdc, 0xf9, 0x3f, 0x90, 0x7a, 0xec, 0x91, 0x53, 0x0b, 0xe9, 0x3f, 0x82, 0x66, 0x3c,
	0x4e, 0xed, 0xa4, 0xae, 0x44, 0xb8, 0x8d, 0xbf, 0x79, 0xef, 0xfb, 0xbe, 0x37, 0xef, 0x8d, 0x07,
	0xbc, 0x1d, 0xa7, 0x6c, 0x6e, 0x93, 0x78, 0x88, 0x63, 0x41, 0x26, 0xd8, 0x9e, 0x1c, 0xfa, 0x58,
	0xa0, 0x43, 0x3b, 0xc0, 0x31, 0xe6, 0x84, 0x5b, 0x09, 0xa3, 0x82, 0xc2, 0x97, 0x32, 0xca, 0x5a,
	0x46, 0x59, 0x3a, 0xaa, 0xf3, 0xa6, 0x22, 0x7b, 0x18, 0x22, 0x12, 0xe9, 0xe4, 0xca, 0xa0, 0x04,
	0x31, 0xb4, 0x0c, 0x6a, 0x05, 0x34, 0xa0, 0x6a, 0x69, 0xcb, 0x95, 0x46, 0xbb, 0x01, 0xa5, 0x41,
	0x88, 0x6d, 0xf5, 0xe5, 0xa7, 0x63, 0x5b, 0x90, 0x08, 0x73, 0x81, 0xa2, 0x24, 0x0b, 0xd8, 0xff,
	0xdd, 0x00, 0xcf, 0x3f, 0x1b, 0x0e, 0xd3, 0x28, 0x0d, 0x91, 0x20, 0x34, 0x3e, 0x25, 0x11, 0x86,
	0x1f, 0x81, 0xc6, 0x90, 0x86, 0x21, 0x12, 0x98, 0xa1, 0xd0, 0x13, 0xf3, 0x04, 0xb7, 0x8d, 0x3d,
	0xa3, 0xf7, 0xd4, 0xdd, 0xbd, 0x83, 0x4f, 0xe7, 0x09, 0x86, 0x3e, 0xe8, 0x24, 0x0c, 0x4f, 0x08,
	0x4d, 0xb9, 0x87, 0x0a, 0x2c, 0x9e, 0x94, 0x69, 0x6f, 0xed, 0x19, 0xbd, 0x7a, 0xbf, 0x63, 0x65,
	0x1e, 0xac, 0xdc, 0x83, 0x75, 0x9a, 0x7b, 0x70, 0x9e, 0x5c, 0x5e, 0x77, 0x6b, 0x17, 0x37, 0x5d,
	0xc3, 0x6d, 0xe7, 0x3c, 0xab, 0x66, 0xf6, 0x7f, 0xd9, 0x02, 0xf0, 0xab, 0xec, 0x30, 0x5d, 0x3c,
	0x45, 0x6c, 0x34, 0x10, 0x48, 0x60, 0xc8, 0x00, 0x5c, 0x53, 0xe4, 0x6d, 0x63, 0xef, 0x51, 0xaf,
	0xde, 0xef, 0x59, 0xf7, 0x1f, 0xb7, 0xb5, 0x4a, 0xee, 0xbc, 0x2f, 0x0d, 0xfc, 0x71, 0xd3, 0x6d,
	0xae, 0xee, 0x70, 0xb7, 0x89, 0x56, 0x21, 0x38, 0x01, 0xad, 0x28, 0x0d, 0x05, 0xf1, 0x98, 0x32,
	0xe2, 0x91, 0x78, 0x84, 0x67, 0x98, 0xb7, 0xb7, 0x1e, 0x56, 0x3d, 0x96, 0x39, 0x99, 0xf7, 0x6f,
	0x64, 0x86, 0xd3, 0xd1, 0xaa, 0x70, 0x75, 0x07, 0x73, 0x17, 0x46, 0x6b, 0xd8, 0xfe, 0x9f, 0x75,
	0xf0, 0x4c, 0x1f, 0x41, 0x56, 0xfc, 0xa7, 0x60, 0x3b, 0x6b, 0xbe, 0xea, 0x4b, 0xbd, 0x6f, 0x56,
	0x49, 0x9f, 0xa8, 0x28, 0xe7, 0xb1, 0x14, 0x74, 0x75, 0x0e, 0xa4, 0xa0, 0x99, 0xf2, 0xd1, 0x38,
	0xaf, 0x82, 0x4b, 0x4a, 0xdd, 0xac, 0x83, 0x2a, 0xa2, 0xf5, 0x0e, 0x38, 0xaf, 0x24, 0xe9, 0xe2,
	0xba, 0xdb, 0xf8, 0x7e, 0x70, 0xf4, 0x65, 0x61, 0xc3, 0x6d, 0x48, 0xf6, 0x62, 0xaf, 0x08, 0x68,
	0x9f, 0x93, 0x78, 0xe6, 0xf1, 0x34, 0x49, 0xc2, 0x79, 0x59, 0xf7, 0xd1, 0x7f, 0xd6, 0xcd, 0x8a,
	0x79, 0x21, 0x19, 0x07, 0x8a, 0xf0, 0x3e, 0x29, 0x9f, 0x32, 0x46, 0xa7, 0x65, 0xa9, 0xc7, 0xff,
	0x47, 0xca, 0x51, 0x84, 0x45, 0xa9, 0x31, 0x78, 0x39, 0xc2, 0x21, 0x0e, 0x90, 0xa0, 0xac, 0x2c,
	0xf4, 0xce, 0x86, 0x42, 0xad, 0x25, 0x5f, 0x51, 0xe7, 0x47, 0xd0, 0xe4, 0x53, 0x94, 0x94, 0x25,
	0xb6, 0x37, 0x94, 0x68, 0x48, 0xaa, 0x22, 0xfb, 0xaf, 0x06, 0x78, 0x4f, 0x4d, 0x43, 0x44, 0x62,
	0x41, 0xe2, 0xc0, 0xcb, 0x7e, 0x3d, 0xed, 0x77, 0x1f, 0x9e, 0x69, 0xd9, 0xf3, 0xe3, 0x2c, 0xe3,
	0x73, 0x99, 0xe0, 0x58, 0x7a, 0x1a, 0x9a, 0xab, 0x3b, 0x5c, 0x5e, 0xaf, 0x35, 0xd0, 0x55, 0x23,
	0x58, 0x82, 0xe0, 0x6f, 0x06, 0x30, 0x55, 0xf3, 0x42, 0xf2, 0x73, 0x4a, 0x46, 0x44, 0xcc, 0xbd,
	0x84, 0xd1, 0x09, 0x19, 0x61, 0x96, 0xbb, 0x7a, 0xa2, 0x5c, 0xf5, 0xab, 0x5c, 0x7d, 0x4b, 0xe2,
	0xd9, 0x77, 0x79, 0xf2, 0x89, 0xce, 0xcd, 0xfc, 0xbd, 0xd1, 0x77, 0xee, 0x75, 0x75, 0x0c, 0x77,
	0x5f, 0x9f, 0x57, 0x6f, 0xc2, 0x73, 0xf0, 0xfc, 0xae, 0xdf, 0xda, 0xcf, 0x53, 0xe5, 0xe7, 0xc3,
	0x2a, 0x3f, 0x47, 0x79, 0x7c, 0xe6, 0xe1, 0x95, 0xf6, 0xd0, 0x28, 0xe3, 0xdc, 0x6d, 0x8c, 0xca,
	0x00, 0x3c, 0x03, 0x75, 0xd5, 0x73, 0x2d, 0x03, 0x94, 0xcc, 0x07, 0x55, 0x32, 0x83, 0x29, 0x4a,
	0x32, 0x05, 0xa8, 0x15, 0xc0, 0x12, 0xe2, 0x2e, 0xe0, 0xcb, 0x35, 0xf4, 0x41, 0x8b, 0xa3, 0x09,
	0x89, 0x03, 0x5e, 0x1e, 0xa7, 0xfa, 0x86, 0xe3, 0x04, 0x35, 0x5b, 0x71, 0xa2, 0x7c, 0xb0, 0x9b,
	0x6b, 0x68, 0xfb, 0xcf, 0x94, 0xfd, 0xb7, 0x95, 0xf6, 0xb3, 0xe8, 0xac, 0x82, 0x17, 0xba, 0x82,
	0x9d, 0x22, 0xca, 0xdd, 0x1d, 0x5e, 0xfc, 0x94, 0x77, 0x02, 0x23, 0x16, 0x97, 0x8b, 0xd8, 0xd9,
	0xf4, 0x4e, 0x48, 0xaa, 0x62, 0x05, 0x67, 0xa0, 0xae, 0xd8, 0xb5, 0xfd, 0xdd, 0x87, 0x4f, 0xff,
	0x0b, 0xc4, 0xe2, 0x95, 0xd3, 0x5f, 0x42, 0xdc, 0x05, 0x78, 0xb9, 0x76, 0xbe, 0xbe, 0xfc, 0xc7,
	0xac, 0x5d, 0x2e, 0x4c, 0xe3, 0x6a, 0x61, 0x1a, 0x7f, 0x2f, 0x4c, 0xe3, 0xe2, 0xd6, 0xac, 0x5d,
	0xdd, 0x9a, 0xb5, 0xbf, 0x6e, 0xcd, 0xda, 0x0f, 0x07, 0x01, 0x11, 0x3f, 0xa5, 0xbe, 0x35, 0xa4,
	0x91, 0x3d, 0xa6, 0x29, 0xfb, 0x44, 0x4c, 0xa9, 0xad, 0x9e, 0xfe, 0x59, 0xe1, 0xf1, 0x97, 0xaf,
	0x31, 0xf7, 0xb7, 0xd5, 0x63, 0xfa, 0xf1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x94, 0xdf,
	0x6f, 0x7e, 0x08, 0x00, 0x00,
}

func (m *AccumulationTime) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccumulationTime) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccumulationTime) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.PreviousAccumulationTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.PreviousAccumulationTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintGenesis(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if len(m.CollateralType) > 0 {
		i -= len(m.CollateralType)
		copy(dAtA[i:], m.CollateralType)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.CollateralType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisRewardState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisRewardState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisRewardState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MultiRewardIndexes) > 0 {
		for iNdEx := len(m.MultiRewardIndexes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MultiRewardIndexes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.AccumulationTimes) > 0 {
		for iNdEx := len(m.AccumulationTimes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccumulationTimes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EarnClaims) > 0 {
		for iNdEx := len(m.EarnClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EarnClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	{
		size, err := m.EarnRewardState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if len(m.SavingsClaims) > 0 {
		for iNdEx := len(m.SavingsClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SavingsClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	{
		size, err := m.SavingsRewardState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if len(m.SwapClaims) > 0 {
		for iNdEx := len(m.SwapClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SwapClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.DelegatorClaims) > 0 {
		for iNdEx := len(m.DelegatorClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegatorClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.JinxLiquidityProviderClaims) > 0 {
		for iNdEx := len(m.JinxLiquidityProviderClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.JinxLiquidityProviderClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.USDFMintingClaims) > 0 {
		for iNdEx := len(m.USDFMintingClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.USDFMintingClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	{
		size, err := m.SwapRewardState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.DelegatorRewardState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.JinxBorrowRewardState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.JinxSupplyRewardState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.USDFRewardState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AccumulationTime) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CollateralType)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.PreviousAccumulationTime)
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GenesisRewardState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AccumulationTimes) > 0 {
		for _, e := range m.AccumulationTimes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.MultiRewardIndexes) > 0 {
		for _, e := range m.MultiRewardIndexes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.USDFRewardState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.JinxSupplyRewardState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.JinxBorrowRewardState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.DelegatorRewardState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.SwapRewardState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.USDFMintingClaims) > 0 {
		for _, e := range m.USDFMintingClaims {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.JinxLiquidityProviderClaims) > 0 {
		for _, e := range m.JinxLiquidityProviderClaims {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DelegatorClaims) > 0 {
		for _, e := range m.DelegatorClaims {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SwapClaims) > 0 {
		for _, e := range m.SwapClaims {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.SavingsRewardState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.SavingsClaims) > 0 {
		for _, e := range m.SavingsClaims {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.EarnRewardState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.EarnClaims) > 0 {
		for _, e := range m.EarnClaims {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AccumulationTime) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccumulationTime: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccumulationTime: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousAccumulationTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.PreviousAccumulationTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisRewardState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisRewardState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisRewardState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumulationTimes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccumulationTimes = append(m.AccumulationTimes, AccumulationTime{})
			if err := m.AccumulationTimes[len(m.AccumulationTimes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MultiRewardIndexes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MultiRewardIndexes = append(m.MultiRewardIndexes, MultiRewardIndex{})
			if err := m.MultiRewardIndexes[len(m.MultiRewardIndexes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field USDFRewardState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.USDFRewardState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JinxSupplyRewardState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.JinxSupplyRewardState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JinxBorrowRewardState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.JinxBorrowRewardState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorRewardState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegatorRewardState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapRewardState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwapRewardState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field USDFMintingClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.USDFMintingClaims = append(m.USDFMintingClaims, USDFMintingClaim{})
			if err := m.USDFMintingClaims[len(m.USDFMintingClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JinxLiquidityProviderClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JinxLiquidityProviderClaims = append(m.JinxLiquidityProviderClaims, JinxLiquidityProviderClaim{})
			if err := m.JinxLiquidityProviderClaims[len(m.JinxLiquidityProviderClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorClaims = append(m.DelegatorClaims, DelegatorClaim{})
			if err := m.DelegatorClaims[len(m.DelegatorClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapClaims = append(m.SwapClaims, SwapClaim{})
			if err := m.SwapClaims[len(m.SwapClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SavingsRewardState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SavingsRewardState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SavingsClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SavingsClaims = append(m.SavingsClaims, SavingsClaim{})
			if err := m.SavingsClaims[len(m.SavingsClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarnRewardState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EarnRewardState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarnClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EarnClaims = append(m.EarnClaims, EarnClaim{})
			if err := m.EarnClaims[len(m.EarnClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
